import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComp from "../../Components/Layout/NavbarComp";
import MainProvider from "../../Providers/MainProvider";
import Footer from "../../Components/Layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChriztianK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainProvider>
          <div className="">
            <NavbarComp />
            <div className="flex flex-col justify-between h-[calc(100vh-72px)]">
              <main className="margin-default ">{children}</main>
              <Footer />
            </div>
          </div>
        </MainProvider>
      </body>
    </html>
  );
}
